### ISSUE TITLE
Startup issues

### ISSUE THREAD

**Issue by sublimator** [justmoon/dassie#28]
<img width="519" alt="image" src="https://github.com/justmoon/dassie/assets/525211/af2a780d-e62d-4956-b0e0-af95329b6a0b">

Maybe just MacOS?

```
                                                                                                                                                                                 (base) ➜  dassie git:(main) rm -rf local 
(base) ➜  dassie git:(main) pnpm start

> @dassie/root@1.0.0 start /Users/nicholasdudfield/projects/dassie
> node packages/app-dev/bin/start-development-server.js

  Dassie//dev

  Starting development server...

  Debug UI: https://localhost/ <- Start here

‼ child exited code=1 signal=null 
‼ error in actor actor="NodeActorsMapped[0]" path="RootActor.RunNodesActor.NodeActorsMapped[0]" 

Error: child exited
    at ChildProcess.handleChildExit (/Users/nicholasdudfield/projects/dassie/packages/app-dev/src/backend/functions/run-child-process.ts:58:20)
    at ChildProcess.emit (node:events:514:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)

‼ error starting nodes

Error: child exited
    at ChildProcess.handleChildExit (/Users/nicholasdudfield/projects/dassie/packages/app-dev/src/backend/functions/run-child-process.ts:58:20)
    at ChildProcess.emit (node:events:514:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)

! proxy connection refused, maybe the node is still starting up port=5003 
! proxy connection refused, maybe the node is still starting up port=5003 
! proxy connection refused, maybe the node is still starting up port=5003 
! proxy connection refused, maybe the node is still starting up port=5003 
! proxy connection refused, maybe the node is still starting up port=5003 
! proxy connection refused, maybe the node is still starting up port=5003 
! proxy connection refused, maybe the node is still starting up port=5002 
! proxy connection refused, maybe the node is still starting up port=5002 
! proxy connection refused, maybe the node is still starting up port=5002 
! proxy connection refused, maybe the node is still starting up port=5002 
! proxy connection refused, maybe the node is still starting up port=5002 
! proxy connection refused, maybe the node is still starting up port=5002 
! proxy connection refused, maybe the node is still starting up port=5004 
! proxy connection refused, maybe the node is still starting up port=5004 
! proxy connection refused, maybe the node is still starting up port=5004 
! proxy connection refused, maybe the node is still starting up port=5004 
! proxy connection refused, maybe the node is still starting up port=5001 
! proxy connection refused, maybe the node is still starting up port=5001 
! proxy connection refused, maybe the node is still starting up port=5001 
! proxy connection refused, maybe the node is still starting up port=5001 
! proxy connection refused, maybe the node is still starting up port=5001 
! proxy connection refused, maybe the node is still starting up port=5001 
! proxy connection refused, maybe the node is still starting up port=5001 
! proxy connection refused, maybe the node is still starting up port=5001 

```

**Comment by sublimator** [comment]
![image](https://github.com/justmoon/dassie/assets/525211/da2039fb-b795-4de6-9093-3c327d58a3aa)

It's alive! 
First it's started for me in many moons
